version: '3.7'
# Service
services:
  # Redis
  Redis-server:
    restart: always
    image: redis:6.2.5
    container_name: app-redis
  # Database MySQL
  mariadb-db:
    restart: always
    image: asce55123/mariadb
    privileged: true
    container_name: app-db
    build: 
      context: ./db
    environment:
      MYSQL_DATABASE: db_store
      MARIADB_ROOT_HOST: root
      MARIADB_ROOT_PASSWORD: springboot
    ports:
      - "3306:3306"
  # APP Server
  app-server:
    restart: always
    image: asce55123/openjdk
    container_name: app-java
    build:
      context: ./java
    ports:
      - "8080:8080"
    environment:
      spring.redis.host: Redis-Server
      DATABASE_USER: root
      DATABASE_PASSWORD: springboot
    depends_on:
      - app-db
    command: ./wait-for-it.sh app-db:3306

# Network